apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: rosscapstonecluster
  region: us-east-1

nodeGroups:
  - name: rossnodegroup
    instanceType: t2.micro
    desiredCapacity: 2
    volumeSize: 5
    ssh:
      allow: false
