version: 2.1

jobs:
  test:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: Test the dockerfile
          command: make test

  build:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push the dockerfile
          command: | #make build-image
            docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESS_CODE
            docker build --tag=jarmanr/capstone .
            docker image ls
            docker push jarmanr/capstone

  create-cluster:
    docker:
      - image: weaveworks/eksctl 
    steps:
      - checkout
      - run:
          name: Create a small 2 node cluster
          command: |
            eksctl create cluster -f cluster_config.yaml

  deploy-to-cluster:
    docker:
     - image: amazon/aws-cli
    steps:
      - run:
          name: Deploy the docker file to the cluster
          command: |
            kubectl create deploy rosscapstonecluster --image=jarmanr/capstone:latest

workflows:
  default:
    jobs:
      - test
      - build
      - create-cluster
      - deploy-to-cluster
          requires: [create-cluster]
