version: 2.1
orbs:
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3.1


jobs:
  test:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: Test the dockerfile
          command: make test

  build:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push the dockerfile
          command: | #make build-image
            docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESS_CODE
            docker build --tag=jarmanr/capstone --build-arg SOMEVAR=blue .
            docker image ls
            docker push jarmanr/capstone

  create-cluster:
    docker:
      - image: 'cimg/python:3.10'
    steps:
      - checkout
      - aws-eks/install-aws-iam-authenticator:
          release-tag: ''
      - aws-eks/create-cluster:
          cluster-name: rosscapstonecluster
          skip-kubectl-install: false
          verbose: 3
          node-type: t2.micro
          nodes-max: 2
          ssh-access: true
          ssh-public-key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC1e9Yu28j2ZZrUaqToFBsfH4FcESujdrosEYqaLxfwcmc+iMYEADBcNhvr7VdSbJeA6J4CHtXH9uibEB/D79jKqNli+ZNL28TTEJtdlfKFJ5lqe8KPLSZW9vSpSFXIwX8Vfe9OnOE2WhEGqakicLdWAUy/FCKlz7HIcSZLwZkM/7+EozpuWD8N0cUe+w5jOP1Wdo/DTTYzAwcyMDzdZHqFmz9yOlPrIg+uHUU5NxStkNGl2G67HxLcU0qhUChCgHjzwTjoVkjhcUTpNe8L7Xv09xbiiw6WaNrL73o2U0w+TXNUME9eKjBhAmJXIjWDhMIQg3T1XAgEes60BBrQxcYF'

  create-service:
    docker:
      - image: 'cimg/python:3.10'
    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: rosscapstonecluster
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          resource-file-path: lb_service.json
          resource-name: service/javalb

  create-deploy:
    #docker:
    # - image: amazon/aws-cli
    #executor: aws-eks/python3
    docker:
      - image: 'cimg/python:3.10'
    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: rosscapstonecluster
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: kubernetes_deployment.json
          resource-name: deployment/rolling1

  update-image:
    docker:
      - image: 'cimg/python:3.10'
    steps:
      - checkout
      - aws-eks/install-aws-iam-authenticator:
          release-tag: ''
      - aws-eks/update-container-image:
          cluster-name: rosscapstonecluster
          container-image-updates: 'rolling1=jarmanr/capstone:latest'
          record: true
          requires:
            - create-deployment
          resource-name: deployment/rolling1

workflows:
  default:
    jobs:
      - test
      - build
      - create-cluster
      - create-service:
          requires:
            - create-cluster
      - create-deploy:
          requires:
            - create-service
      #- update-image
      - aws-eks/update-container-image:
          cluster-name: rosscapstonecluster
          container-image-updates: 'rolling1=jarmanr/capstone:latest'
          get-rollout-status: true
          show-kubectl-command: true
          requires:
            - create-deploy
          resource-name: deployment/rolling1


